minimumReleaseAgeExclude:
  - '@tssuite/testproject_2@0.1.4 || 0.1.5'
  - '@tssuite/testproject_3@0.1.7 || 0.1.8'
  - '@tssuite/helix-js@0.1.0'
overrides:
  "@tssuite/testproject_2": link:../testproject_2
  "@tssuite/testproject_3": link:../testproject_3
