// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/testproject_1_version.test.ts.

/** The version of the `@tssuite/testproject_1` package. */
export const testproject1Version = '0.5.4';
